[package]
name = "falconload"
version = "0.0.1"
edition = "2021"
authors = ["John Law <poyea@pm.me>"]
license = "MIT"
description = "Lightweight UDP-based load testing toolkit"
repository = "https://github.com/poyea/falconload"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.20.1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
clap = { version = "4.0", features = ["derive"] }
